# Generated by Django 4.1.5 on 2023-07-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service_Name',
            new_name='serviceName',
        ),
    ]
