# Generated by Django 4.1.5 on 2023-07-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0003_alter_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='web',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DoctorSchedule', to='webs.web'),
            preserve_default=False,
        ),
    ]
