# Generated by Django 4.1.5 on 2023-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0004_alter_doctorschedule_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(),
        ),
    ]
