# Generated by Django 4.1.5 on 2023-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0005_alter_doctorschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Detailedaddress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='FileNnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('غير محدد', 'غير محدد'), ('ذكر ', 'ذكر'), ('انثى', 'انثى')], max_length=30, null=True),
        ),
    ]
