# Generated by Django 4.1.5 on 2023-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0006_alter_patient_detailedaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
