# Generated by Django 4.1.5 on 2023-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0007_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='currencyـname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
