# Generated by Django 4.1.5 on 2023-07-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0008_web_currencyـname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='Click_whatsapp',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='views',
        ),
        migrations.RemoveField(
            model_name='categories_pixel',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='categories_pixel',
            name='click_whatsapp',
        ),
        migrations.RemoveField(
            model_name='categories_pixel',
            name='views',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='Click_whatsapp',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='views',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Click_whatsapp',
        ),
        migrations.RemoveField(
            model_name='service',
            name='views',
        ),
        migrations.RemoveField(
            model_name='web',
            name='Click_booking',
        ),
        migrations.RemoveField(
            model_name='web',
            name='Click_whatsapp',
        ),
        migrations.RemoveField(
            model_name='web',
            name='Click_whatsapp_Categories',
        ),
        migrations.RemoveField(
            model_name='web',
            name='views',
        ),
        migrations.RemoveField(
            model_name='web',
            name='views_Categories',
        ),
        migrations.RemoveField(
            model_name='web',
            name='views_checkout',
        ),
        migrations.RemoveField(
            model_name='web',
            name='views_confirmation',
        ),
    ]
