# Generated by Django 4.1.5 on 2023-07-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0009_remove_categories_click_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories_pixel',
            name='booking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='categories_pixel',
            name='click_whatsapp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='categories_pixel',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
