# Generated by Django 4.1.5 on 2023-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0010_categories_pixel_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='Appointment_password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Report_password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='settings_password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
